### ISSUE TITLE
Crash with some libraries.

### ISSUE THREAD

**Issue by Txnix** [DustinRepo/JexClient#13]
If you use JexClient with Fabric API, BCLib, Flytre Lib and GeckoLib it crashes, but if you remove 1 of the libraries it doesn't crash.
![Screenshot (8)](https://user-images.githubusercontent.com/45898130/137219357-3e7163c8-7796-40aa-9d24-9da53a021a84.png)

**Comment by DustinRepo** [comment]
If you are still having this issue feel free to join the discord for better support, but I will be closing this ticket as it's been so long without a reply
