### ISSUE TITLE
Tunneller width not working properly + Third person seems weird

### ISSUE THREAD

**Issue by JKnaps** [DustinRepo/JexClient#15]
Setting the width for tunneller to 1 makes it so the character constantly walks forward without mining any blocks. Setting it to 2 makes it so the character mines a 3 wide tunnel instead of 2 wide.

Also, the character in the third person seems very "stiff" compared to when the mod isn't installed. I don't know how to describe it, but it's kinda like the character is always facing forward with the camera, unlike vanilla where the character can rotate a bit independent from the camera view.

**Comment by DustinRepo** [comment]
The tunneller issue will be worked on, and the 3rd person weirdness is caused by attempting to show baritone rotations, even when baritone is not loaded or running, and will for sure be fixed next update. Thanks for the input
